apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "px-pem.fullname" . }}
  labels:
    app.kubernetes.io/name: px-pem
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: px-pem
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: px-pem
        app.kubernetes.io/instance: {{ .Release.Name }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ default (printf "%s" (include "px-pem.fullname" .)) .Values.serviceAccount.name }}
      hostPID: {{ .Values.pod.hostPID }}
      hostNetwork: {{ .Values.pod.hostNetwork }}
      dnsPolicy: {{ .Values.pod.dnsPolicy }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      containers:
        - name: pem
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: PL_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: PL_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: PL_HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: PX_STANDALONE_PEM_PORT
              value: "{{ .Values.port }}"
            - name: PL_LOCAL_K8S_UPDATE_UDS
              value: "/var/run/px-pem/mds.sock"
          ports:
            - name: grpc
              containerPort: {{ .Values.port }}
          volumeMounts:
            - name: host-root
              mountPath: /host
              readOnly: true
            - name: sys
              mountPath: /sys
              readOnly: true
            - name: px-pem-run
              mountPath: /var/run/px-pem
              readOnly: false
        - name: watcher
          image: "{{ .Values.watcher.image.repository }}:{{ .Values.watcher.image.tag }}"
          imagePullPolicy: {{ .Values.watcher.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.watcher.resources | nindent 12 }}
          env:
            - name: PL_LOCAL_K8S_UPDATE_UDS
              value: "/var/run/px-pem/mds.sock"
          volumeMounts:
            - name: px-pem-run
              mountPath: /var/run/px-pem
              readOnly: false
      volumes:
        - name: host-root
          hostPath:
            path: /
            type: Directory
        - name: sys
          hostPath:
            path: /sys
            type: Directory
        - name: px-pem-run
          emptyDir: {}