{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (printf "%s" (include "px-pem.fullname" .)) .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: px-pem
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
